sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.21.2
  matrix:
    - GW_MACHINE_NAME=raspberry-pi
    - GW_MACHINE_NAME=raspberrypi3

language: python

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

install:
  - pip install yq
  # Ensure we can build ARM images
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  # Build images
  - docker-compose build
  # Does it run?
  - |
    IMAGE=$(docker-compose config | yq -r .services.octoprint.image)
    echo "OctoPrint image is: ${IMAGE}"
    docker run --rm "${IMAGE}" /opt/octoprint/OctoPrint/venv/bin/octoprint --version

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true
