# Docker-compose file for Octoprint Containers

# Version 2.1 for resin compatibility
version: '2.1'

volumes:
  octoprint_vol: {}

services:
  # Octoprint itself
  octoprint:
    build:
      context: octoprint
      args:
        release: latest
    image: amedee/octoprint-octoprint
    restart: always
    privileged: true
    volumes:
      - octoprint_vol:/opt/octoprint/data
      # Uncomment next line for "Plain Docker" setup
      # - /run/dbus:/host/run/dbus
    labels:
      io.resin.features.dbus: '1'
  # Webcam stream
  webcam:
    build:
      context: webcam
    image: amedee/octoprint-webcam
    restart: always
    privileged: true
    environment:
      WEBCAM_INPUT: "${WEBCAM_INPUT:-input_raspicam.so -fps 5}"
      WEBCAM_START: "${WEBCAM_START:-true}"
  # http/https proxy
  haproxy:
    build:
      context: haproxy
    image: amedee/octoprint-haproxy
    restart: always
    depends_on:
      - octoprint
      - webcam
    volumes:
      - octoprint_vol:/opt/haproxy/data
    ports:
      - "80:80"
      - "443:443"
