# Docker-compose file for Octoprint Containers

# Version 2.1 for resin compatibility
version: '2.1'

volumes:
  octoprint_vol: {}
  octoprint_2_vol: {}

services:
  # Octoprint 1
  octoprint:
    build:
      context: octoprint
      args:
        OP_MACHINE_NAME:
        release: latest
    image: amedee/octoprint-octoprint
    restart: always
    privileged: true
    volumes:
      - octoprint_vol:/opt/octoprint/data
      # Uncomment next line for "Plain Docker" setup
      # - /run/dbus:/host/run/dbus
    labels:
      io.resin.features.dbus: '1'
  # Octoprint 2
  octoprint_2:
    build:
      context: octoprint_2
      args:
        OP_MACHINE_NAME:
        release: latest
    image: amedee/octoprint-octoprint
    restart: always
    privileged: true
    volumes:
      - octoprint_2_vol:/opt/octoprint/data
      # Uncomment next line for "Plain Docker" setup
      # - /run/dbus:/host/run/dbus
    labels:
      io.resin.features.dbus: '2'
  # Webcam stream
  webcam:
    build:
      context: webcam
      args:
        OP_MACHINE_NAME:
    image: amedee/octoprint-webcam
    restart: always
    privileged: true
    environment:
      WEBCAM_INPUT: "${WEBCAM_INPUT:-input_raspicam.so -fps 5}"
      WEBCAM_START: "${WEBCAM_START:-true}"
  # http/https proxy
  haproxy:
    build:
      context: haproxy
      args:
        OP_MACHINE_NAME:
    image: amedee/octoprint-haproxy
    restart: always
    depends_on:
      - octoprint
      - webcam
    volumes:
      - octoprint_vol:/opt/haproxy/data
    ports:
      - "80:80"
      - "443:443"
